In [1]:
import pandas as pd

In [2]:
train=pd.read_csv('twitter_training.csv')

In [3]:
train.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [5]:
train.shape

(74681, 4)

In [6]:
train.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    686
dtype: int64

Data Exploration

In [7]:
train['Positive'].value_counts()

Positive
Negative      22542
Positive      20831
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [ ]:
train.duplicated().sum()

np.int64(2700)

In [9]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 74681 entries, 0 to 74680
Data columns (total 4 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   2401                                                   74681 non-null  int64
 1   Borderlands                                            74681 non-null  str
 2   Positive                                               74681 non-null  str
 3   im getting on borderlands and i will murder you all ,  73995 non-null  str
dtypes: int64(1), str(3)
memory usage: 11.4 MB

Data Cleaning

In [10]:
train=train.dropna()

In [11]:
train.isnull().sum()

2401                                                     0
Borderlands                                              0
Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

In [12]:
train.duplicated().sum()

np.int64(2340)

In [13]:
train.drop_duplicates(inplace=True)

In [14]:
train.duplicated().sum()

np.int64(0)

In [15]:
train.shape

(71655, 4)

In [16]:
train.drop(columns=['2401','Borderlands'],inplace=True)

In [17]:
train

       Positive im getting on borderlands and i will murder you all ,
0      Positive  I am coming to the borders and I will kill you...
1      Positive  im getting on borderlands and i will kill you ...
2      Positive  im coming on borderlands and i will murder you...
3      Positive  im getting on borderlands 2 and i will murder ...
4      Positive  im getting into borderlands and i can murder y...
...         ...                                                ...
74676  Positive  Just realized that the Windows partition of my...
74677  Positive  Just realized that my Mac window partition is ...
74678  Positive  Just realized the windows partition of my Mac ...
74679  Positive  Just realized between the windows partition of...
74680  Positive  Just like the windows partition of my Mac is l...

[71655 rows x 2 columns]

In [20]:
train.rename(columns={'Positive':'Sentiment','im getting on borderlands and i will murder you all ,':'Tweet'},inplace=True)

In [21]:
train

      Sentiment                                              Tweet
0      Positive  I am coming to the borders and I will kill you...
1      Positive  im getting on borderlands and i will kill you ...
2      Positive  im coming on borderlands and i will murder you...
3      Positive  im getting on borderlands 2 and i will murder ...
4      Positive  im getting into borderlands and i can murder y...
...         ...                                                ...
74676  Positive  Just realized that the Windows partition of my...
74677  Positive  Just realized that my Mac window partition is ...
74678  Positive  Just realized the windows partition of my Mac ...
74679  Positive  Just realized between the windows partition of...
74680  Positive  Just like the windows partition of my Mac is l...

[71655 rows x 2 columns]

In [26]:
train[(train['Sentiment']=='Positive') | (train['Sentiment']=='Negative') | (train['Sentiment']=='Neutral')]

      Sentiment                                              Tweet
0      Positive  I am coming to the borders and I will kill you...
1      Positive  im getting on borderlands and i will kill you ...
2      Positive  im coming on borderlands and i will murder you...
3      Positive  im getting on borderlands 2 and i will murder ...
4      Positive  im getting into borderlands and i can murder y...
...         ...                                                ...
74676  Positive  Just realized that the Windows partition of my...
74677  Positive  Just realized that my Mac window partition is ...
74678  Positive  Just realized the windows partition of my Mac ...
74679  Positive  Just realized between the windows partition of...
74680  Positive  Just like the windows partition of my Mac is l...

[59118 rows x 2 columns]

In [27]:
train.head()

  Sentiment                                              Tweet
0  Positive  I am coming to the borders and I will kill you...
1  Positive  im getting on borderlands and i will kill you ...
2  Positive  im coming on borderlands and i will murder you...
3  Positive  im getting on borderlands 2 and i will murder ...
4  Positive  im getting into borderlands and i can murder y...

In [28]:
train['Sentiment'].value_counts()

Sentiment
Negative      21698
Positive      19712
Neutral       17708
Irrelevant    12537
Name: count, dtype: int64

Feature Encoding

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
label=LabelEncoder()

In [31]:
train['Sentiment']=label.fit_transform(train['Sentiment'])

In [32]:
train

       Sentiment                                              Tweet
0              3  I am coming to the borders and I will kill you...
1              3  im getting on borderlands and i will kill you ...
2              3  im coming on borderlands and i will murder you...
3              3  im getting on borderlands 2 and i will murder ...
4              3  im getting into borderlands and i can murder y...
...          ...                                                ...
74676          3  Just realized that the Windows partition of my...
74677          3  Just realized that my Mac window partition is ...
74678          3  Just realized the windows partition of my Mac ...
74679          3  Just realized between the windows partition of...
74680          3  Just like the windows partition of my Mac is l...

[71655 rows x 2 columns]

In [34]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [36]:
tokenizer=Tokenizer(oov_token='Nothing')

In [37]:
tokenizer.fit_on_texts(train['Tweet'])

In [38]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'and': 5,
 'a': 6,
 'of': 7,
 'is': 8,
 'in': 9,
 'for': 10,
 'this': 11,
 'it': 12,
 'you': 13,
 'on': 14,
 'my': 15,
 'that': 16,
 'com': 17,
 'with': 18,
 'game': 19,
 'so': 20,
 'be': 21,
 'me': 22,
 'have': 23,
 'just': 24,
 'but': 25,
 'not': 26,
 'are': 27,
 'all': 28,
 'at': 29,
 'was': 30,
 'like': 31,
 'out': 32,
 'from': 33,
 '2': 34,
 'your': 35,
 'now': 36,
 'get': 37,
 'we': 38,
 'as': 39,
 'pic': 40,
 'twitter': 41,
 'they': 42,
 'has': 43,
 'if': 44,
 'one': 45,
 't': 46,
 'do': 47,
 'about': 48,
 'good': 49,
 'can': 50,
 'play': 51,
 'no': 52,
 'will': 53,
 'an': 54,
 'new': 55,
 'really': 56,
 'when': 57,
 'up': 58,
 'love': 59,
 'unk': 60,
 "i'm": 61,
 'what': 62,
 'more': 63,
 'by': 64,
 'time': 65,
 'johnson': 66,
 'how': 67,
 'people': 68,
 'or': 69,
 'some': 70,
 'why': 71,
 '3': 72,
 'see': 73,
 'shit': 74,
 'co': 75,
 'been': 76,
 "it's": 77,
 'best': 78,
 'still': 79,
 '’': 80,
 'facebook': 81,
 'https': 82,
 'games': 83,
 'got': 84,
 '1': 85,
 'go': 86,
 'great': 87,
 'amazon': 88,
 'even': 89,
 'playing': 90,
 'who': 91,
 'xbox': 92,
 'because': 93,
 'google': 94,
 'fucking': 95,
 'them': 96,
 'rhandlerr': 97,
 '4': 98,
 'please': 99,
 'had': 100,
 'microsoft': 101,
 'dead': 102,
 'there': 103,
 'fuck': 104,
 'us': 105,
 'verizon': 106,
 'only': 107,
 'back': 108,
 'much': 109,
 'their': 110,
 'our': 111,
 'after': 112,
 '5': 113,
 'red': 114,
 's': 115,
 'going': 116,
 'he': 117,
 'fifa': 118,
 'would': 119,
 'am': 120,
 'first': 121,
 'know': 122,
 'over': 123,
 'tv': 124,
 'its': 125,
 "don't": 126,
 "can't": 127,
 'home': 128,
 'make': 129,
 'these': 130,
 'again': 131,
 'pubg': 132,
 'player': 133,
 'very': 134,
 'day': 135,
 'than': 136,
 '…': 137,
 'fun': 138,
 'today': 139,
 'here': 140,
 'also': 141,
 'most': 142,
 'nvidia': 143,
 'borderlands': 144,
 'gta': 145,
 'want': 146,
 'fix': 147,
 'ever': 148,
 '2020': 149,
 'bad': 150,
 'twitch': 151,
 'video': 152,
 'then': 153,
 'thank': 154,
 'never': 155,
 'ban': 156,
 'call': 157,
 'world': 158,
 'battlefield': 159,
 'thanks': 160,
 'every': 161,
 'overwatch': 162,
 'wait': 163,
 'series': 164,
 'year': 165,
 'off': 166,
 'watch': 167,
 'right': 168,
 'eamaddennfl': 169,
 'too': 170,
 'think': 171,
 'x': 172,
 'team': 173,
 'getting': 174,
 'last': 175,
 'amazing': 176,
 'work': 177,
 'redemption': 178,
 'being': 179,
 'his': 180,
 'v': 181,
 'nba2k': 182,
 '10': 183,
 'ps5': 184,
 "i've": 185,
 'rainbow6game': 186,
 'u': 187,
 'news': 188,
 'any': 189,
 'well': 190,
 'league': 191,
 'guys': 192,
 'into': 193,
 'happy': 194,
 'youtu': 195,
 'live': 196,
 'played': 197,
 'legends': 198,
 'help': 199,
 'man': 200,
 'did': 201,
 'black': 202,
 'youtube': 203,
 'i’m': 204,
 'actually': 205,
 'say': 206,
 'fortnite': 207,
 'depot': 208,
 'damn': 209,
 'next': 210,
 'always': 211,
 'everyone': 212,
 'stop': 213,
 'looks': 214,
 'need': 215,
 'made': 216,
 'years': 217,
 'duty': 218,
 'another': 219,
 'look': 220,
 'down': 221,
 'csgo': 222,
 'players': 223,
 'should': 224,
 'big': 225,
 'm': 226,
 'warcraft': 227,
 'could': 228,
 'ghostrecon': 229,
 'while': 230,
 'come': 231,
 'something': 232,
 'were': 233,
 'creed': 234,
 'buy': 235,
 'stream': 236,
 'via': 237,
 'which': 238,
 'since': 239,
 'way': 240,
 'same': 241,
 'free': 242,
 'many': 243,
 'other': 244,
 'better': 245,
 'win': 246,
 'hearthstone': 247,
 'finally': 248,
 'money': 249,
 'already': 250,
 'online': 251,
 'him': 252,
 'such': 253,
 'excited': 254,
 'it’s': 255,
 'thing': 256,
 'nice': 257,
 'life': 258,
 'take': 259,
 '100': 260,
 '20': 261,
 'two': 262,
 'her': 263,
 'support': 264,
 'update': 265,
 'playstation': 266,
 'give': 267,
 'hate': 268,
 'ass': 269,
 '6': 270,
 'pc': 271,
 'bit': 272,
 'store': 273,
 'lol': 274,
 'italy': 275,
 'before': 276,
 'care': 277,
 'check': 278,
 'ly': 279,
 'wow': 280,
 'keep': 281,
 'someone': 282,
 'war': 283,
 'awesome': 284,
 'having': 285,
 'doing': 286,
 'gonna': 287,
 'top': 288,
 'oh': 289,
 'where': 290,
 'through': 291,
 'days': 292,
 'does': 293,
 'health': 294,
 'done': 295,
 'lot': 296,
 'wtf': 297,
 'real': 298,
 'old': 299,
 'night': 300,
 'feel': 301,
 'trying': 302,
 'super': 303,
 'looking': 304,
 'pretty': 305,
 'access': 306,
 'cool': 307,
 'long': 308,
 'dota': 309,
 'playapex': 310,
 'use': 311,
 'im': 312,
 'everything': 313,
 'things': 314,
 'ubisoft': 315,
 'both': 316,
 'servers': 317,
 'account': 318,
 'those': 319,
 'hell': 320,
 'making': 321,
 'nothing': 322,
 'hey': 323,
 'favorite': 324,
 'baby': 325,
 'literally': 326,
 'said': 327,
 'god': 328,
 'little': 329,
 'makes': 330,
 'guy': 331,
 "that's": 332,
 'season': 333,
 '7': 334,
 'card': 335,
 'anyone': 336,
 'uk': 337,
 'cyberpunk': 338,
 'working': 339,
 'mobile': 340,
 'week': 341,
 'hard': 342,
 'stupid': 343,
 'company': 344,
 'worst': 345,
 'start': 346,
 'probably': 347,
 'problem': 348,
 '2077': 349,
 'gaming': 350,
 'hope': 351,
 'try': 352,
 'show': 353,
 'ops': 354,
 'hours': 355,
 'cold': 356,
 'until': 357,
 'almost': 358,
 'against': 359,
 'phone': 360,
 'let': 361,
 'friends': 362,
 'won': 363,
 'ea': 364,
 'miss': 365,
 'find': 366,
 'part': 367,
 "doesn't": 368,
 'whole': 369,
 'sure': 370,
 'details': 371,
 'times': 372,
 'service': 373,
 'few': 374,
 'can’t': 375,
 'story': 376,
 'around': 377,
 'yet': 378,
 'anything': 379,
 'banned': 380,
 'cs': 381,
 'lost': 382,
 'app': 383,
 'don’t': 384,
 'tell': 385,
 'powder': 386,
 'crazy': 387,
 'full': 388,
 'own': 389,
 'without': 390,
 'using': 391,
 'stuff': 392,
 'maybe': 393,
 'tonight': 394,
 'apex': 395,
 '19': 396,
 'd': 397,
 'beautiful': 398,
 'internet': 399,
 'pay': 400,
 'far': 401,
 'end': 402,
 'absolutely': 403,
 'open': 404,
 'coming': 405,
 '2k': 406,
 'bf4db': 407,
 'used': 408,
 'put': 409,
 "didn't": 410,
 'cant': 411,
 'release': 412,
 'chance': 413,
 'thought': 414,
 'fact': 415,
 'enjoy': 416,
 'w': 417,
 'console': 418,
 'ps4': 419,
 'interesting': 420,
 'says': 421,
 'community': 422,
 'may': 423,
 'e': 424,
 'she': 425,
 '0': 426,
 'minutes': 427,
 'ranked': 428,
 'callofduty': 429,
 'sad': 430,
 'org': 431,
 'went': 432,
 '21': 433,
 'business': 434,
 'kill': 435,
 "you're": 436,
 'enough': 437,
 'dont': 438,
 '30': 439,
 'order': 440,
 'trash': 441,
 'month': 442,
 'mode': 443,
 'point': 444,
 'gets': 445,
 'run': 446,
 'gameplay': 447,
 "won't": 448,
 'epic': 449,
 'reason': 450,
 'tt': 451,
 'wrong': 452,
 'away': 453,
 'broken': 454,
 'content': 455,
 "assassin's": 456,
 'though': 457,
 'line': 458,
 'vaccine': 459,
 'huge': 460,
 'read': 461,
 'post': 462,
 'sorry': 463,
 'y’all': 464,
 'watching': 465,
 'soon': 466,
 '12': 467,
 'p': 468,
 'tried': 469,
 'perfect': 470,
 'bro': 471,
 'due': 472,
 'bought': 473,
 'million': 474,
 'match': 475,
 'occurred': 476,
 'hit': 477,
 'change': 478,
 'assassins': 479,
 '8': 480,
 'feels': 481,
 'cause': 482,
 'madden': 483,
 'ago': 484,
 'screen': 485,
 'music': 486,
 "i'll": 487,
 'forward': 488,
 'covid': 489,
 'instead': 490,
 'worth': 491,
 'event': 492,
 'grand': 493,
 'able': 494,
 'myself': 495,
 'seems': 496,
 'skin': 497,
 'definitely': 498,
 '9': 499,
 'net': 500,
 '15': 501,
 'system': 502,
 'i’ve': 503,
 'during': 504,
 'might': 505,
 'once': 506,
 'streaming': 507,
 'friend': 508,
 'cod': 509,
 'pro': 510,
 'services': 511,
 'price': 512,
 'morning': 513,
 'second': 514,
 'latest': 515,
 'problems': 516,
 'selling': 517,
 'months': 518,
 'found': 519,
 'else': 520,
 'high': 521,
 'launch': 522,
 "y'all": 523,
 'wanted': 524,
 'currently': 525,
 'name': 526,
 'yes': 527,
 'started': 528,
 'job': 529,
 'tomorrow': 530,
 'terrible': 531,
 'based': 532,
 'comes': 533,
 'fan': 534,
 'power': 535,
 'mean': 536,
 'experience': 537,
 'person': 538,
 'idea': 539,
 'place': 540,
 'die': 541,
 'dota2': 542,
 'data': 543,
 'came': 544,
 'saying': 545,
 'seeing': 546,
 'character': 547,
 'half': 548,
 'seen': 549,
 'needs': 550,
 'r': 551,
 '”': 552,
 'took': 553,
 'face': 554,
 'graphics': 555,
 'server': 556,
 'buying': 557,
 'level': 558,
 'share': 559,
 'ok': 560,
 'funny': 561,
 'honestly': 562,
 'exciting': 563,
 'called': 564,
 'worse': 565,
 'cards': 566,
 'remember': 567,
 'taken': 568,
 'ift': 569,
 'wanna': 570,
 'must': 571,
 'finished': 572,
 'single': 573,
 'luck': 574,
 'follow': 575,
 'seriously': 576,
 'different': 577,
 'join': 578,
 'dlvr': 579,
 'completely': 580,
 'fans': 581,
 '•': 582,
 'playhearthstone': 583,
 'list': 584,
 'c': 585,
 'link': 586,
 'patch': 587,
 'pre': 588,
 'warzone': 589,
 'proud': 590,
 'weekend': 591,
 'homedepot': 592,
 'together': 593,
 'guess': 594,
 'sucks': 595,
 'talc': 596,
 'talk': 597,
 'kinda': 598,
 'issues': 599,
 'later': 600,
 'shot': 601,
 'anymore': 602,
 'yo': 603,
 'three': 604,
 'tweet': 605,
 'hi': 606,
 'page': 607,
 'windows': 608,
 'odyssey': 609,
 'entire': 610,
 'social': 611,
 'eu': 612,
 'left': 613,
 'below': 614,
 'hour': 615,
 'trump': 616,
 'myteam': 617,
 'yall': 618,
 're': 619,
 'holy': 620,
 'tech': 621,
 'set': 622,
 'kind': 623,
 'birthday': 624,
 'moments': 625,
 'trailer': 626,
 'despite': 627,
 'less': 628,
 'taking': 629,
 'least': 630,
 'wish': 631,
 'gold': 632,
 'mad': 633,
 'rewards': 634,
 'sick': 635,
 'waiting': 636,
 'hear': 637,
 'earned': 638,
 'lmao': 639,
 'loved': 640,
 'understand': 641,
 'ur': 642,
 'ghost': 643,
 'annoying': 644,
 'switch': 645,
 'family': 646,
 'omg': 647,
 'movie': 648,
 'n': 649,
 'deal': 650,
 'easy': 651,
 'achievement': 652,
 'points': 653,
 'bitch': 654,
 'leave': 655,
 'white': 656,
 'code': 657,
 'running': 658,
 'bring': 659,
 'saw': 660,
 'believe': 661,
 'each': 662,
 'incredible': 663,
 'move': 664,
 'girl': 665,
 'issue': 666,
 'ready': 667,
 'rtx': 668,
 'n2k': 669,
 'y': 670,
 'apple': 671,
 'breakpoint': 672,
 'pass': 673,
 'glad': 674,
 'past': 675,
 'action': 676,
 'either': 677,
 'b': 678,
 "let's": 679,
 'error': 680,
 'sometimes': 681,
 'killed': 682,
 'apps': 683,
 'cannot': 684,
 'death': 685,
 'fortnitegame': 686,
 'early': 687,
 'final': 688,
 'class': 689,
 'daily': 690,
 'starting': 691,
 'living': 692,
 'told': 693,
 'blizzard': 694,
 'major': 695,
 'break': 696,
 'videos': 697,
 'companies': 698,
 'congratulations': 699,
 'add': 700,
 'small': 701,
 'quite': 702,
 'happened': 703,
 'yesterday': 704,
 'welcome': 705,
 'sounds': 706,
 'instagram': 707,
 'house': 708,
 'toxic': 709,
 'easports': 710,
 'step': 711,
 'goes': 712,
 'yeah': 713,
 'suck': 714,
 'under': 715,
 'tired': 716,
 'giving': 717,
 'history': 718,
 'review': 719,
 'gotta': 720,
 'market': 721,
 'truly': 722,
 'wikipedia': 723,
 'boy': 724,
 'don': 725,
 'group': 726,
 'products': 727,
 'totally': 728,
 'heart': 729,
 'battle': 730,
 'customer': 731,
 'hot': 732,
 'j': 733,
 'original': 734,
 'version': 735,
 'smh': 736,
 'bc': 737,
 'gen': 738,
 'fantastic': 739,
 'global': 740,
 'f': 741,
 'nba': 742,
 'mind': 743,
 'modern': 744,
 'edition': 745,
 'number': 746,
 'ubisoftsupport': 747,
 "we're": 748,
 '“': 749,
 'book': 750,
 'india': 751,
 'biggest': 752,
 'between': 753,
 'delayed': 754,
 'hello': 755,
 'beta': 756,
 've': 757,
 'talking': 758,
 'leagueoflegends': 759,
 'characters': 760,
 'turn': 761,
 "what's": 762,
 'gift': 763,
 'greatest': 764,
 'car': 765,
 "haven't": 766,
 'article': 767,
 'ronnie2k': 768,
 'crap': 769,
 'dude': 770,
 'complete': 771,
 'especially': 772,
 'bullshit': 773,
 'teams': 774,
 'kills': 775,
 'true': 776,
 'sound': 777,
 'media': 778,
 'fire': 779,
 'fps': 780,
 'thinking': 781,
 'behind': 782,
 'main': 783,
 "they're": 784,
 'updates': 785,
 'longer': 786,
 'decided': 787,
 'report': 788,
 'email': 789,
 'keeps': 790,
 '11': 791,
 'drop': 792,
 'special': 793,
 "there's": 794,
 'absolute': 795,
 'o': 796,
 'gone': 797,
 'city': 798,
 'feeling': 799,
 'lose': 800,
 'kids': 801,
 'franchise': 802,
 'id': 803,
 'available': 804,
 'weeks': 805,
 'connection': 806,
 'beluba': 807,
 'pls': 808,
 'performance': 809,
 'design': 810,
 'that’s': 811,
 'spend': 812,
 'sold': 813,
 'late': 814,
 'close': 815,
 'speed': 816,
 'current': 817,
 'cute': 818,
 'en': 819,
 'cancer': 820,
 'official': 821,
 'including': 822,
 'released': 823,
 '3080': 824,
 'star': 825,
 'controller': 826,
 'clips': 827,
 'commission': 828,
 'wins': 829,
 'men': 830,
 '–': 831,
 'shows': 832,
 'works': 833,
 'channel': 834,
 'stay': 835,
 'sony': 836,
 'okay': 837,
 'garbage': 838,
 '000': 839,
 'box': 840,
 'rt': 841,
 'racist': 842,
 'retweet': 843,
 'plays': 844,
 'test': 845,
 'warfare': 846,
 'alone': 847,
 'low': 848,
 'playoverwatch': 849,
 'future': 850,
 'moment': 851,
 'within': 852,
 '24': 853,
 'side': 854,
 'word': 855,
 'esports': 856,
 'art': 857,
 'random': 858,
 'women': 859,
 'means': 860,
 '50': 861,
 'joke': 862,
 'sell': 863,
 'massive': 864,
 'enjoyed': 865,
 'ridiculous': 866,
 'plus': 867,
 'head': 868,
 'ya': 869,
 'safe': 870,
 'canada': 871,
 'search': 872,
 'technology': 873,
 'website': 874,
 'takes': 875,
 'gamer': 876,
 'worked': 877,
 'imagine': 878,
 'losing': 879,
 'chat': 880,
 'fast': 881,
 'appreciate': 882,
 'computer': 883,
 'killing': 884,
 'hero': 885,
 'spent': 886,
 'campaign': 887,
 'information': 888,
 'coronavirus': 889,
 'yourself': 890,
 'winning': 891,
 'fake': 892,
 'stopped': 893,
 'cuz': 894,
 'stock': 895,
 'possible': 896,
 'trust': 897,
 'ai': 898,
 'gpu': 899,
 'police': 900,
 'tho': 901,
 'control': 902,
 'disappointed': 903,
 'customers': 904,
 'powerful': 905,
 'auto': 906,
 '99': 907,
 'heard': 908,
 'died': 909,
 'item': 910,
 'insane': 911,
 'date': 912,
 'wants': 913,
 'prime': 914,
 'nfl': 915,
 'hyped': 916,
 'twice': 917,
 'save': 918,
 'drive': 919,
 'poverty': 920,
 'others': 921,
 'product': 922,
 'gave': 923,
 'become': 924,
 'map': 925,
 'dear': 926,
 'ordered': 927,
 'site': 928,
 'government': 929,
 'dog': 930,
 'fight': 931,
 'stuck': 932,
 'mixer': 933,
 'continue': 934,
 'dark': 935,
 'geforce': 936,
 'unit': 937,
 'digital': 938,
 'exactly': 939,
 'happens': 940,
 'bugs': 941,
 'dumb': 942,
 'g': 943,
 'iphone': 944,
 'forever': 945,
 'quality': 946,
 'rest': 947,
 'short': 948,
 '14': 949,
 'party': 950,
 'shooting': 951,
 'seem': 952,
 'mut': 953,
 'download': 954,
 'somehow': 955,
 'boys': 956,
 'l': 957,
 'boring': 958,
 'state': 959,
 'piece': 960,
 'result': 961,
 '25': 962,
 'important': 963,
 "i'd": 964,
 'broke': 965,
 'valhalla': 966,
 'pick': 967,
 '13': 968,
 'song': 969,
 'school': 970,
 'sense': 971,
 'actual': 972,
 'tch': 973,
 'voice': 974,
 'log': 975,
 'sweet': 976,
 'matter': 977,
 'activision': 978,
 'received': 979,
 'vs': 980,
 'weird': 981,
 'workers': 982,
 'trial': 983,
 'eahelp': 984,
 'dlc': 985,
 "he's": 986,
 'lets': 987,
 '2019': 988,
 'missing': 989,
 'valorant': 990,
 'load': 991,
 'cyberpunkgame': 992,
 'finish': 993,
 "isn't": 994,
 '16': 995,
 'simply': 996,
 'hold': 997,
 'skins': 998,
 'lie': 999,
 'listen': 1000,
 ...}

In [39]:
tokenizer.word_counts

OrderedDict([('i', 28807),
             ('am', 1741),
             ('coming', 481),
             ('to', 28649),
             ('the', 44005),
             ('borders', 12),
             ('and', 26369),
             ('will', 3285),
             ('kill', 437),
             ('you', 12048),
             ('all', 5528),
             ('im', 680),
             ('getting', 1261),
             ('on', 11958),
             ('borderlands', 1501),
             ('murder', 78),
             ('2', 4324),
             ('me', 6889),
             ('into', 1161),
             ('can', 3434),
             ('so', 7641),
             ('spent', 187),
             ('a', 23965),
             ('few', 535),
             ('hours', 567),
             ('making', 636),
             ('something', 937),
             ('for', 15447),
             ('fun', 1546),
             ('if', 3620),
             ("don't", 1684),
             ('know', 1720),
             ('huge', 409),
             ('fan', 340),
             ('maya', 22),
             ('is', 17527),
             ('one', 3585),
             ('of', 19230),
             ('my', 11686),
             ('favorite', 621),
             ('characters', 227),
             ('decided', 219),
             ('make', 1653),
             ('myself', 373),
             ('wallpaper', 14),
             ('pc', 785),
             ('here', 1531),
             ('original', 235),
             ('image', 71),
             ('versus', 18),
             ('creation', 7),
             ('made', 1044),
             ('enjoy', 457),
             ('pic', 3804),
             ('twitter', 3740),
             ('com', 9583),
             ('mlsi5wf9jg', 4),
             ('couple', 156),
             ('doing', 730),
             ('that', 10136),
             ("i'm", 3066),
             ("here's", 142),
             ('picture', 115),
             ('compared', 79),
             ('have', 6629),
             ('rhandlerr', 1990),
             ('2010', 70),
             ('was', 5335),
             ('rock', 84),
             ('hard', 585),
             ('la', 86),
             ('varlope', 4),
             ('rare', 34),
             ('powerful', 180),
             ('handsome', 71),
             ('jackpot', 9),
             ('3', 2773),
             ('xbox', 2131),
             ('dlvr', 311),
             ('it', 14092),
             ('rmtrgf', 6),
             ('dfr', 7),
             ('vita', 12),
             ('but', 6290),
             ('1', 2261),
             ('live', 1141),
             ('music', 384),
             ('sega', 27),
             ('from', 4370),
             ('e', 448),
             ('like', 4838),
             ('london', 24),
             ('de', 124),
             ('2011', 54),
             ('first', 1733),
             ('session', 80),
             ('in', 15569),
             ('long', 691),
             ('time', 2943),
             ('where', 726),
             ('actually', 1091),
             ('had', 1978),
             ('really', 3216),
             ('satisfying', 48),
             ('combat', 62),
             ('experience', 338),
             ('got', 2269),
             ('some', 2820),
             ('good', 3476),
             ('kills', 223),
             ('this', 14404),
             ('fighting', 76),
             ('enjoyed', 193),
             ('rather', 141),
             ('real', 711),
             ('nice', 849),
             ('wait', 1308),
             ('hot', 237),
             ('row', 159),
             ('bad', 1431),
             ('did', 1104),
             ('biggest', 229),
             ('dissappoinment', 4),
             ('life', 844),
             ('came', 333),
             ('out', 4458),
             ('year', 1293),
             ('ago', 385),
             ('fuck', 1933),
             ('disappointment', 73),
             ('male', 22),
             ('hanging', 73),
             ('back', 1887),
             ('last', 1254),
             ('we', 3870),
             ('finished', 315),
             ('finally', 887),
             ('yas', 10),
             ('thank', 1399),
             ('everyone', 1062),
             ('try', 571),
             ('stream', 927),
             ('tomorrow', 343),
             ('not', 6274),
             ('might', 364),
             ('irl', 52),
             ('streams', 83),
             ('while', 942),
             ('awayu', 4),
             ('shall', 41),
             ('see', 2744),
             ('much', 1841),
             ('raids', 29),
             ('mompou', 6),
             ('mumpow', 6),
             ('megamagwitch', 4),
             ('kfdmitch', 3),
             ('find', 551),
             ('yes', 345),
             ("i'll", 383),
             ('maybe', 490),
             ("we'll", 66),
             ('thanks', 1330),
             ('up', 3180),
             ('get', 3899),
             ('haircut', 8),
             ("wasn't", 100),
             ('would', 1745),
             ('still', 2424),
             ('be', 7019),
             ('hawaii', 4),
             ('megamagwife', 1),
             ('fendmitch', 1),
             ('update', 798),
             ('guys', 1162),
             ('even', 2215),
             ('go', 2244),
             ('hope', 573),
             ('10', 1220),
             ('never', 1394),
             ('both', 643),
             ('or', 2861),
             ('4', 1989),
             ('hey', 626),
             ('use', 687),
             ('how', 2895),
             ('many', 899),
             ('their', 1839),
             ('man', 1117),
             ('gearbox', 30),
             ('needs', 331),
             ('fix', 1473),
             ('dissapointing', 3),
             ('drops', 108),
             ('new', 3226),
             ('dlc', 162),
             ('cant', 466),
             ('fine', 160),
             ('farm', 31),
             ('bosses', 20),
             ('mayhem', 64),
             ('legendary', 129),
             ('drop', 216),
             ('anywhere', 119),
             ('else', 352),
             ('6', 786),
             ('sucks', 297),
             ('alot', 40),
             ('these', 1652),
             ('disappointing', 94),
             ('elsewhere', 13),
             ('disssapointing', 1),
             ('bethesda', 33),
             ('completely', 310),
             ('days', 723),
             ('having', 740),
             ('foot', 38),
             ('unk', 3103),
             ('force', 115),
             ('check', 766),
             ('epic', 419),
             ('streamer', 107),
             ('watch', 1290),
             ('striptease', 2),
             ('our', 1832),
             ('big', 986),
             ('blaming', 12),
             ('sight', 31),
             ('tardiness', 2),
             ('little', 608),
             ('bit', 785),
             ('called', 319),
             ('early', 254),
             ('work', 1246),
             ("can't", 1663),
             ('sorry', 407),
             ('loves', 74),
             ('twitch', 1415),
             ('tv', 1701),
             ('punnisenpai', 3),
             ('borderland', 14),
             ('morning', 359),
             ('catch', 78),
             ('love', 3156),
             ('guilty', 40),
             ('sobriety', 1),
             ('borderline', 9),
             ('why', 2797),
             ('does', 721),
             ('every', 1315),
             ('slicked', 4),
             ('hair', 119),
             ('haven’t', 97),
             ('heard', 179),
             ('bangs', 5),
             ('stupid', 585),
             ('assholes', 48),
             ('border', 53),
             ('countries', 34),
             ('your', 4243),
             ('fallen', 33),
             ('off', 1292),
             ('are', 5984),
             ('aliens', 23),
             ('beth', 9),
             ('she', 447),
             ('haven', 45),
             ('’', 2418),
             ('t', 3563),
             ('enough', 433),
             ('gray', 11),
             ('practically', 20),
             ('france', 5),
             ('greedy', 48),
             ('45', 48),
             ('what', 3041),
             ('going', 1768),
             ('finish', 161),
             ('today', 1541),
             ("i've", 1201),
             ('commands', 26),
             ('set', 280),
             ('looking', 702),
             ('forward', 383),
             ('starting', 253),
             ('about', 3490),
             ('hour', 283),
             ('start', 581),
             ('an', 3243),
             ('installed', 79),
             ('events', 98),
             ('look', 1034),
             ('20', 819),
             ('cleaning', 14),
             ('just', 6588),
             ('her', 811),
             ('volume', 23),
             ('awesome', 741),
             ('server', 325),
             ('imma', 76),
             ('probably', 581),
             ('play', 3400),
             ('tps', 11),
             ("that'll", 18),
             ('playing', 2158),
             ("it's", 2548),
             ("that'yer", 1),
             ('ll', 114),
             ('video', 1406),
             ('own', 493),
             ('profzeroo', 5),
             ('w', 456),
             ('3‼', 2),
             ('him', 864),
             ('buff', 160),
             ('ly', 766),
             ('2wmmip5', 6),
             ('say', 1082),
             ('shouts', 19),
             ('chat', 189),
             ('chance', 459),
             ('shout', 124),
             ('upcoming', 91),
             ('profzero', 1),
             ('p', 402),
             ('–', 205),
             ('also', 1519),
             ('shows', 205),
             ('via', 927),
             ('at', 5415),
             ('officially', 95),
             ('series', 1298),
             ('its', 1696),
             ('movies', 55),
             ('invitation', 11),
             ('invites', 3),
             ('yessssssss', 4),
             ('fick', 6),
             ('yessssss', 2),
             ('hate', 792),
             ('easy', 268),
             ('modifier', 11),
             ('event', 377),
             ('won’t', 129),
             ('forever', 170),
             ('most', 1516),
             ('i’ve', 367),
             ('game', 8136),
             ('since', 911),
             ('they', 3674),
             ('added', 136),
             ('them', 2009),
             ('horrible', 124),
             ('modifiers', 22),
             ('please', 1981),
             ('give', 796),
             ('option', 134),
             ('turn', 227),
             ('pls', 211),
             ('simple', 138),
             ('chaos', 40),
             ("won't", 421),
             ("that's", 600),
             ('terrible', 342),
             ('saying', 333),
             ('day', 1559),
             ('9', 370),
             ('ability', 50),
             ('thinking', 220),
             ('total', 138),
             ('won', 555),
             ('absolutely', 482),
             ('ridiculous', 193),
             ('ve', 228),
             ('almost', 563),
             ('do', 3536),
             ('best', 2528),
             ('taken', 317),
             ('past', 258),
             ('until', 564),
             ('send', 133),
             ('grounded', 5),
             ('looked', 142),
             ('pretty', 699),
             ('cool', 694),
             ('despite', 278),
             ('tier', 74),
             ('unfunny', 7),
             ('writing', 77),
             ('became', 97),
             ('yet', 526),
             ('another', 1036),
             ('survival', 23),
             ('crafting', 5),
             ('can’t', 531),
             ('shitty', 148),
             ('trend', 38),
             ('die', 335),
             ('crappy', 45),
             ('grosskreutz', 1),
             ('spelling', 12),
             ('turned', 140),
             ('crap', 225),
             ('mod', 39),
             ('deep', 92),
             ('fifth', 21),
             ('format', 23),
             ('ultimately', 14),
             ('mobile', 588),
             ('top', 728),
             ('annoying', 270),
             ('seriously', 313),
             ('appreciate', 188),
             ('sonic', 42),
             ('concepts', 12),
             ('praxis', 3),
             ('valenzuela', 4),
             ('landa', 5),
             ('posas', 5),
             ('thread', 67),
             ('together', 299),
             ('talk', 296),
             ('multimodal', 6),
             ('listening', 89),
             ('soundwalks', 5),
             ('frameworks', 4),
             ('participatory', 5),
             ('action', 258),
             ('research', 78),
             ('testimonios', 4),
             ('thoughtful', 5),
             ('resonant', 6),
             ('intersections', 6),
             ('sound', 222),
             ('practices', 6),
             ('combine', 14),
             ('lecture', 12),
             ('testimonies', 1),
             ('evaluate', 2),
             ('valensela', 1),
             ('pozas', 1),
             ('conversation', 36),
             ('walks', 4),
             ('areas', 24),
             ('joint', 15),
             ('studies', 23),
             ('etc', 109),
             ('amazing', 1253),
             ('moreno', 1),
             ('recordings', 8),
             ('field', 44),
             ('by', 2954),
             ('electronic', 18),
             ('creating', 62),
             ('visual', 21),
             ('digital', 172),
             ('interviews', 8),
             ('thoughts', 59),
             ('reflected', 3),
             ('conversations', 18),
             ('actions', 17),
             ('klein', 1),
             ('brought', 142),
             ('experiences', 21),
             ('ethical', 1),
             ('provocative', 1),
             ('submit', 34),
             ('complaint', 29),
             ('ceo', 47),
             ("isn't", 161),
             ('paying', 99),
             ('his', 1231),
             ('staff', 90),
             ('bonuses', 20),
             ('file', 90),
             ("doesn't", 547),
             ('pay', 484),
             ('employees', 158),
             ('competitors', 17),
             ('suppose', 24),
             ("isn'ain", 1),
             ('entire', 289),
             ('now', 4069),
             ('any', 1172),
             ('offering', 27),
             ('fuckin', 124),
             ('trash', 429),
             ('damn', 1074),
             ('rubbish', 21),
             ('fucking', 2033),
             ('thrash', 43),
             ('shit', 2679),
             ('35', 70),
             ('played', 1137),
             ('through', 725),
             ('actual', 164),
             ('great', 2221),
             ('guns', 60),
             ('feel', 707),
             ('once', 364),
             ('felt', 154),
             ('needed', 129),
             ('grind', 85),
             ('story', 531),
             ('other', 897),
             ('hand', 145),
             ('very', 1581),
             ('eventual', 6),
             ('cutscene', 18),
             ('skip', 23),
             ('weapons', 109),
             ('funny', 320),
             ('sequence', 8),
             ('occasional', 4),
             ('slip', 8),
             ('open', 482),
             ('someone', 758),
             ('side', 197),
             ('endless', 30),
             ('5', 1800),
             ('were', 935),
             ('sure', 544),
             ('oh', 727),
             ("yes'm", 1),
             ('extended', 27),
             ('loving', 158),
             ('ghostlifestyle', 5),
             ('cans', 16),
             ('anyone', 591),
             ('drink', 26),
             ('ghost', 271),
             ('drinks', 9),
             ('ghostlive', 1),
             ('three', 292),
             ('want', 1481),
             ('come', 941),
             ('meet', 115),
             ('lovely', 95),
             ('gaming', 577),
             ('goddesses', 5),
             ('gambling', 31),
             ('beautiful', 486),
             ('gods', 40),
             ('16', 161),
             ('green', 88),
             ('hell', 637),
             ('halloween', 51),
             ('month', 427),
             ('already', 871),
             ('march', 65),
             ('pulling', 29),
             ('bitch', 266),
             ('slut', 15),
             ('miracle', 27),
             ('ok', 321),
             ('bombs', 18),
             ('over', 1718),
             ('baghdad', 5),
             ('anything', 525),
             ('gets', 424),
             ('hype', 108),
             ('concept', 61),
             ('a1', 9),
             ('gives', 131),
             ('baghad', 1),
             ('seeing', 332),
             ('take', 844),
             ('sir', 113),
             ('case', 147),
             ('earth', 65),
             ('rpg', 47),
             ('uninstalled', 42),
             ('games', 2272),
             ('space', 115),
             ('uninstall', 22),
             ('room', 143),
             ('deleted', 127),
             ('watching', 405),
             ('bleeding', 17),
             ('edge', 143),
             ('clever', 20),
             ('cross', 127),
             ('between', 229),
             ('overwatch', 1315),
             ('domination', 9),
             ('mode', 427),
             ('as', 3825),
             ('crossroads', 1),
             ('future', 198),
             ('2016', 125),
             ('fantasy', 125),
             ('non', 92),
             ('bioshock', 30),
             ('switch', 270),
             ('count', 70),
             ('desert', 29),
             ('montana', 1),
             ('after', 1802),
             ('platinum', 53),
             ('loot', 121),
             ('booty', 16),
             ('lot', 716),
             ('has', 3647),
             ('named', 46),
             ('reason', 419),
             ('laptop', 108),
             ('run', 424),
             ('war', 753),
             ('thunder', 29),
             ('warframe', 10),
             ('high', 351),
             ('settings', 92),
             ('moment', 198),
             ('launch', 351),
             ('csgo', 1016),
             ('computer', 188),
             ('crashes', 145),
             ('whole', 547),
             ('breaks', 33),
             ('down', 1028),
             ('firefox', 36),
             ('plus', 193),
             ('no', 3333),
             ('easily', 86),
             ('currently', 346),
             ('dare', 44),
             ('mind', 232),
             ('software', 132),
             ('mount', 49),
             ('act', 95),
             ('king', 117),
             ('speeds', 54),
             ('jumping', 66),
             ('more', 3033),
             ('dlcs', 13),
             ('vibing', 3),
             ('playlists', 15),
             ('vibe', 41),
             ('dropping', 73),
             ('quality', 170),
             ('720p', 4),
             ('makes', 606),
             ('difference', 70),
             ('well', 1171),
             ('runs', 111),
             ('dumb', 171),
             ('internet', 486),
             ('lmao', 273),
             ('heyitscece', 3),
             ('streaming', 363),
             ('vibrating', 1),
             ('lowering', 5),
             ('jon', 27),
             ('downloading', 53),
             ('tumb', 3),
             ('enter', 117),
             ('gunner', 12),
             ('seat', 26),
             ('fear', 89),
             ('step', 246),
             ('trench', 1),
             ('then', 1402),
             ('wav1bacr5j', 4),
             ('wikipedia', 240),
             ('org', 440),
             ('v', 1227),
             ('omg', 269),
             ('ever', 1467),
             ('thwarted', 4),
             ('bank', 82),
             ('foiled', 1),
             ('threatened', 20),
             ('who', 2158),
             ('late', 209),
             ('trip', 50),
             ('seems', 373),
             ('broken', 415),
             ('with', 8773),
             ('m10', 6),
             ('rates', 18),
             ('constantly', 113),
             ('less', 278),
             ('than', 1553),
             ('lower', 93),

In [40]:
tokenizer.document_count

71655

In [41]:
len(tokenizer.word_index)

33784

In [42]:
sequences=tokenizer.texts_to_sequences(train['Tweet'])

In [43]:
sequences

[[3, 120, 405, 4, 2, 6691, 5, 3, 53, 435, 13, 28],
 [312, 174, 14, 144, 5, 3, 53, 435, 13, 28],
 [312, 405, 14, 144, 5, 3, 53, 1811, 13, 28],
 [312, 174, 14, 144, 34, 5, 3, 53, 1811, 13, 22, 28],
 [312, 174, 193, 144, 5, 3, 50, 1811, 13, 28],
 [20,
  3,
  886,
  6,
  374,
  355,
  321,
  232,
  10,
  138,
  44,
  13,
  126,
  122,
  3,
  120,
  6,
  460,
  144,
  534,
  5,
  4458,
  8,
  45,
  7,
  15,
  324,
  760,
  20,
  3,
  787,
  4,
  129,
  495,
  6,
  6088,
  10,
  15,
  271,
  140,
  8,
  2,
  734,
  1937,
  5105,
  2,
  9423,
  3,
  216,
  416,
  40,
  41,
  17,
  18112],
 [20,
  3,
  886,
  6,
  1031,
  7,
  355,
  286,
  232,
  10,
  138,
  44,
  13,
  126,
  122,
  16,
  61,
  6,
  460,
  144,
  534,
  5,
  4458,
  8,
  45,
  7,
  15,
  324,
  760,
  3,
  787,
  4,
  129,
  6,
  6088,
  10,
  15,
  271,
  1104,
  2,
  734,
  1304,
  1790,
  4,
  2,
  9423,
  3,
  216,
  23,
  138,
  40,
  41,
  17,
  18112],
 [20,
  3,
  886,
  6,
  374,
  355,
  286,
  232,
  10,
  138,
  44,
  13,
  126,
  122,
  61,
  6,
  460,
  144,
  534,
  5,
  4458,
  8,
  45,
  7,
  15,
  324,
  760],
 [20,
  3,
  886,
  6,
  374,
  355,
  321,
  232,
  10,
  138,
  44,
  13,
  126,
  122,
  3,
  120,
  6,
  460,
  97,
  534,
  5,
  4458,
  8,
  45,
  7,
  15,
  324,
  760,
  20,
  3,
  787,
  4,
  129,
  495,
  6,
  6088,
  10,
  15,
  271,
  140,
  8,
  2,
  734,
  1937,
  5105,
  2,
  9423,
  3,
  216,
  416,
  40,
  41,
  17,
  18112],
 [1962,
  20,
  3,
  886,
  6,
  374,
  355,
  321,
  232,
  10,
  138,
  44,
  13,
  126,
  122,
  3,
  120,
  6,
  460,
  97,
  534,
  5,
  4458,
  8,
  45,
  7,
  15,
  324,
  760,
  20,
  3,
  787,
  4,
  129,
  495,
  6,
  6088,
  10,
  15,
  271,
  140,
  8,
  2,
  734,
  1937,
  5105,
  2,
  9423,
  3,
  216,
  416,
  40,
  41,
  17,
  18112],
 [30],
 [1693, 342, 1657, 18113, 3291, 905, 1938, 8308, 144, 72, 92, 579, 12, 10111],
 [1693, 342, 1657, 18113, 3291, 905, 1938, 8308, 144, 72, 92, 579, 12, 10111],
 [1693, 342, 1657, 18113, 3291, 905, 1938, 8308, 144, 72, 92, 9424, 12, 10111],
 [1693,
  342,
  1657,
  6692,
  3291,
  25,
  905,
  1938,
  8308,
  144,
  85,
  92,
  579,
  12,
  10111],
 [196,
  1693,
  342,
  486,
  1657,
  1657,
  18113,
  3291,
  2,
  905,
  196,
  1938,
  3,
  8308,
  144,
  72,
  3875,
  92,
  579,
  33,
  12,
  424,
  10111],
 [3, 342, 31, 22, 3291, 4177, 1233, 1938, 2359, 144, 72, 92, 579, 12, 10111],
 [16,
  30,
  2,
  121,
  144,
  1772,
  9,
  6,
  308,
  65,
  290,
  3,
  205,
  100,
  6,
  56,
  2580,
  2148,
  537,
  3,
  84,
  70,
  56,
  49,
  775],
 [11,
  30,
  2,
  121,
  144,
  1772,
  9,
  6,
  308,
  65,
  290,
  3,
  205,
  100,
  6,
  56,
  2580,
  1845,
  537,
  3,
  84,
  70,
  56,
  49,
  775],
 [16,
  30,
  2,
  121,
  144,
  1772,
  9,
  6,
  308,
  65,
  290,
  3,
  205,
  865,
  6,
  56,
  2580,
  2148,
  537,
  3,
  84,
  70,
  1115,
  49,
  775],
 [16,
  3,
  30,
  2,
  121,
  298,
  144,
  1772,
  9,
  6,
  257,
  308,
  163,
  65,
  290,
  3,
  205,
  100,
  6,
  56,
  2580,
  2148,
  537,
  5,
  3,
  84,
  70,
  56,
  49,
  775],
 [16,
  30,
  2,
  121,
  144,
  1772,
  9,
  6,
  732,
  1007,
  290,
  3,
  205,
  100,
  6,
  56,
  150,
  2148,
  537,
  3,
  201,
  70,
  56,
  49,
  775],
 [2, 752, 18114, 9, 15, 258, 544, 32, 6, 165, 484, 104, 144, 72],
 [2, 752, 1900, 7, 15, 258, 544, 6, 165, 484],
 [2, 752, 18114, 9, 15, 258, 405, 32, 6, 165, 484, 104, 144, 72],
 [10,
  2,
  752,
  4459,
  18114,
  9,
  15,
  258,
  544,
  1901,
  32,
  6,
  165,
  65,
  484,
  104,
  144,
  72],
 [2, 752, 18114, 9, 15, 258, 544, 108, 175, 165, 484, 104, 144, 175],
 [38,
  572,
  144,
  72,
  248,
  7725,
  154,
  13,
  10,
  1901,
  32,
  212,
  12,
  30,
  138,
  3,
  53,
  352,
  4,
  236,
  530,
  25,
  44,
  26,
  3,
  505,
  20,
  70,
  2427,
  1709,
  230,
  18115,
  38,
  2925,
  73,
  154,
  13,
  20,
  109,
  10,
  2,
  3668,
  10112,
  10113,
  18116,
  5,
  21847],
 [38,
  248,
  248,
  366,
  144,
  72,
  527,
  154,
  13,
  28,
  10,
  1901,
  32,
  12,
  30,
  138,
  487,
  352,
  4,
  236,
  530,
  25,
  44,
  26,
  393,
  70,
  2427,
  1709,
  2049,
  73,
  160,
  10,
  2,
  3668,
  10112,
  10113,
  18116,
  5,
  21847],
 [154,
  13,
  10,
  1901,
  58,
  212,
  12,
  30,
  138,
  487,
  352,
  4,
  37,
  6,
  8827,
  530,
  25,
  44,
  12,
  1462,
  10,
  22,
  70,
  2427,
  1709,
  119,
  79,
  21,
  9,
  18117,
  2049,
  73,
  154,
  13,
  20,
  109,
  10,
  2,
  10112,
  10113,
  26649,
  5,
  26650,
  3668],
 [38,
  572,
  144,
  72,
  265,
  7725,
  154,
  13,
  10,
  1901,
  32,
  192,
  12,
  30,
  138,
  3,
  53,
  352,
  4,
  236,
  5,
  89,
  44,
  26,
  3,
  505,
  20,
  70,
  2427,
  1709,
  230,
  18115,
  38,
  2925,
  86,
  154,
  13,
  20,
  109,
  10,
  2,
  3668,
  10112,
  10113,
  18116,
  5,
  351],
 [38,
  572,
  144,
  72,
  5,
  248,
  7725,
  154,
  13,
  212,
  10,
  1901,
  32,
  212,
  12,
  30,
  138,
  3,
  53,
  352,
  4,
  129,
  236,
  530,
  25,
  44,
  26,
  3,
  505,
  129,
  20,
  70,
  2427,
  1709,
  230,
  18115,
  183,
  38,
  155,
  2925,
  73,
  154,
  13,
  316,
  20,
  109,
  10,
  2,
  3668,
  10112,
  10113,
  69,
  18116,
  5,
  98,
  21847],
 [38,
  572,
  144,
  72,
  248,
  7725,
  323,
  13,
  10,
  1901,
  32,
  20,
  12,
  30,
  138,
  3,
  53,
  352,
  16,
  236,
  530,
  5,
  44,
  26,
  3,
  505,
  311,
  70,
  2427,
  1709,
  33,
  18115,
  38,
  2925,
  73,
  154,
  13,
  20,
  109,
  67,
  243,
  3668,
  10112,
  10113,
  201,
  5,
  110],
 [200,
  3584,
  56,
  550,
  4,
  147,
  11,
  21848,
  1365,
  9,
  2,
  55,
  144,
  72,
  985,
  411,
  21,
  1002,
  4,
  3500,
  4755,
  14,
  2106,
  183,
  4,
  37,
  85,
  1198,
  792,
  230,
  1272,
  520,
  3,
  37,
  270,
  183,
  1365,
  56,
  595,
  2973],
 [200,
  3584,
  56,
  550,
  4,
  147,
  130,
  1544,
  1365,
  9,
  2,
  55,
  144,
  72,
  985,
  10,
  3500,
  4755,
  14,
  2106,
  183,
  4,
  37,
  6,
  1198,
  792,
  230,
  3,
  37,
  270,
  183,
  1365,
  6382],
 [200,
  3584,
  56,
  550,
  4,
  147,
  11,
  26651,
  1365,
  9,
  2,
  55,
  144,
  72,
  985,
  411,
  21,
  1002,
  4,
  3500,
  4755,
  14,
  2106,
  183,
  4,
  37,
  85,
  1198,
  792,
  230,
  6382,
  3,
  37,
  270,
  183,
  1365,
  56,
  595,
  2973],
 [200,
  3342,
  56,
  550,
  4,
  147,
  11,
  21848,
  1365,
  5,
  2,
  55,
  144,
  72,
  12,
  411,
  21,
  1002,
  4,
  3500,
  4755,
  14,
  2106,
  183,
  4,
  37,
  85,
  1198,
  792,
  230,
  1272,
  520,
  3,
  37,
  270,
  183,
  1365,
  56,
  595],
 [200,
  3584,
  56,
  550,
  4,
  147,
  11,
  21848,
  1365,
  9,
  2,
  580,
  55,
  144,
  72,
  292,
  985,
  3,
  411,
  424,
  21,
  1002,
  285,
  4,
  21,
  3500,
  4755,
  14,
  2106,
  183,
  4,
  424,
  37,
  85,
  1198,
  3081,
  792,
  230,
  1272,
  520,
  3,
  37,
  270,
  183,
  1365,
  12,
  56,
  595,
  4,
  2973],
 [60,
  3584,
  56,
  65,
  4,
  147,
  11,
  183,
  1365,
  9,
  2,
  55,
  144,
  72,
  985,
  69,
  21,
  1002,
  4,
  1305,
  4755,
  14,
  2106,
  183,
  4,
  37,
  6,
  1198,
  792,
  230,
  212,
  520,
  3,
  37,
  270,
  183,
  1365,
  56,
  550,
  2973],
 [278, 32, 11, 449, 1375],
 [278, 32, 11, 449, 1375],
 [167, 11, 449, 24060],
 [278, 32, 111, 449, 1375],
 [278, 32, 11, 225, 449, 1375],
 [278, 60, 11, 449, 1375],
 [6693,
  3501,
  10,
  24061,
  6,
  329,
  272,
  7,
  144,
  3,
  84,
  564,
  9,
  687,
  10,
  177,
  530,
  20,
  3,
  127,
  129,
  58,
  65,
  463,
  15,
  1875,
  151,
  124,
  21849],
 [6,
  272,
  7,
  6089,
  3,
  30,
  564,
  4,
  177,
  530,
  513,
  20,
  3,
  127,
  1812,
  58,
  463,
  15,
  59,
  151,
  124,
  21849],
 [2974,
  7,
  26652,
  6,
  272,
  7,
  6,
  8309,
  3,
  30,
  564,
  4,
  177,
  687,
  530,
  20,
  3,
  127,
  1812,
  58],
 [10,
  6693,
  3501,
  10,
  24061,
  6,
  329,
  272,
  7,
  144,
  3,
  84,
  564,
  9,
  687,
  10,
  177,
  530,
  20,
  3,
  127,
  129,
  58,
  65,
  463,
  15,
  1875,
  151,
  124,
  21849],
 [28],
 [71,
  293,
  31,
  161,
  200,
  9,
  144,
  23,
  18118,
  108,
  1273,
  1503,
  13,
  908,
  7,
  13770,
  13,
  343,
  2581],
 [71, 31, 161, 200, 9, 2390, 3292, 23, 13, 26, 908, 7, 13770, 13, 343, 2581],
 [71,
  31,
  212,
  520,
  9,
  2,
  2390,
  3292,
  23,
  35,
  1273,
  3343,
  166,
  23,
  13,
  26,
  908,
  16,
  13,
  27,
  343,
  4292],
 [71,
  293,
  31,
  60,
  200,
  9,
  144,
  23,
  18118,
  108,
  1273,
  69,
  13,
  908,
  7,
  13770,
  13,
  343,
  2581],
 [71,
  8310,
  293,
  31,
  161,
  200,
  9,
  144,
  23,
  425,
  18118,
  16,
  108,
  1273,
  2703,
  80,
  46,
  13,
  908,
  437,
  7,
  7212,
  13770,
  13,
  343,
  2581],
 [71,
  293,
  4756,
  161,
  200,
  9,
  13771,
  23,
  18118,
  108,
  1273,
  1503,
  13,
  908,
  7,
  13770,
  2,
  2582,
  2581],
 [],
 [],
 [2583],
 [62],
 [116,
  4,
  993,
  58,
  144,
  34,
  139,
  185,
  84,
  70,
  55,
  3967,
  622,
  58,
  5,
  120,
  304,
  488,
  4,
  6,
  49,
  236,
  691,
  9,
  48,
  120,
  615],
 [3,
  53,
  993,
  144,
  34,
  139,
  3,
  23,
  70,
  55,
  3967,
  622,
  58,
  5,
  120,
  304,
  488,
  4,
  6,
  49,
  236,
  346,
  9,
  48,
  54,
  615],
 [61,
  116,
  4,
  993,
  144,
  34,
  139,
  3,
  23,
  70,
  55,
  3967,
  1791,
  5,
  61,
  304,
  488,
  4,
  6,
  49,
  236],
 [116,
  4,
  993,
  58,
  144,
  34,
  139,
  185,
  84,
  70,
  55,
  1488,
  622,
  58,
  5,
  120,
  220,
  488,
  4,
  6,
  49,
  236,
  691,
  9,
  48,
  261,
  615],
 [116,
  4,
  993,
  993,
  6090,
  58,
  144,
  34,
  139,
  185,
  24,
  84,
  263,
  70,
  55,
  3967,
  622,
  28,
  58,
  5,
  120,
  304,
  488,
  12,
  4,
  6,
  49,
  236,
  691,
  9,
  48,
  120,
  615],
 [116,
  4,
  993,
  58,
  4293,
  34,
  139,
  185,
  84,
  70,
  284,
  556,
  622,
  58,
  5,
  8,
  304,
  488,
  4,
  6,
  49,
  236,
  691,
  9,
  48,
  120,
  615],
 [1846, 347, 51, 70, 144, 7213, 9, 6, 272, 5106, 21, 138],
 [1846, 8, 347, 90, 6, 272, 7, 6089, 7213, 16, 53, 21, 138],
 [1846, 53, 347, 51, 70, 2390, 7213, 9, 6, 272, 77, 116, 4, 21, 138],
 [1846, 347, 51, 196, 144, 7213, 9, 6, 272, 5106, 21, 138],
 [10, 1846, 347, 51, 70, 144, 7213, 9, 6, 272, 26653, 1313, 21, 6, 138],
 [1846, 347, 84, 70, 152, 7213, 9, 6, 272, 5106, 129, 138],
 [45,
  7,
  111,
  389,
  13772,
  8,
  196,
  417,
  144,
  24062,
  1812,
  252,
  140,
  1003,
  279,
  10114,
  206,
  1375,
  4936,
  9,
  880,
  10,
  6,
  413,
  4,
  21,
  9,
  6,
  405,
  1375,
  4936,
  1234,
  32],
 [45,
  7,
  111,
  389,
  13772,
  8,
  196,
  417,
  144,
  72,
  1812,
  252,
  140,
  1003,
  279,
  10114,
  206,
  1375,
  4936,
  9,
  880,
  10,
  6,
  413,
  4,
  21,
  9,
  54,
  1590,
  45,
  1375,
  4936,
  1234,
  32],
 [45,
  7,
  111,
  389,
  26654,
  196,
  417,
  144,
  72,
  1812,
  252,
  140,
  1003,
  279,
  10114,
  206,
  236,
  4936,
  9,
  880,
  10,
  6,
  880,
  10,
  6,
  413,
  4,
  21,
  9,
  6,
  405,
  236,
  4936,
  1234,
  32],
 [45,
  7,
  111,
  389,
  13772,
  8,
  196,
  144,
  24062,
  1812,
  252,
  140,
  1003,
  279,
  10114,
  468,
  206,
  70,
  4936,
  9,
  880,
  831,
  6,
  413,
  4,
  21,
  9,
  6,
  405,
  141,
  1234,
  32],
 [45,
  7,
  111,
  832,
  389,
  13772,
  8,
  196,
  237,
  417,
  29,
  144,
  72,
  5,
  60,
  1812,
  252,
  140,
  2,
  1003,
  279,
  4,
  10114,
  4,
  206,
  1375,
  4936,
  9,
  880,
  10,
  6,
  413,
  4,
  1529,
  21,
  9,
  6,
  164,
  405,
  1375,
  4936,
  85,
  1234,
  32],
 [45,
  7,
  125,
  389,
  2333,
  8,
  196,
  417,
  13772,
  72,
  1812,
  252,
  33,
  1003,
  279,
  10114,
  10,
  1375,
  4936,
  9,
  7214,
  69,
  6,
  413,
  4,
  21,
  32,
  6,
  405,
  28,
  72,
  21850],
 [104, 18119],
 [10115, 24063],
 [104, 18119],
 [104, 18119, 60],
 [6, 104, 18119],
 [104, 13],
 [3,
  268,
  16,
  11,
  651,
  2106,
  7215,
  492,
  14,
  2106,
  1199,
  175,
  945,
  11,
  8,
  2,
  142,
  138,
  503,
  100,
  9,
  2,
  19,
  239,
  42,
  1144,
  96,
  1235,
  4460,
  144,
  99,
  267,
  22,
  2,
  1156,
  4,
  51,
  2106,
  183,
  25,
  761,
  2,
  4460,
  166,
  808],
 [3,
  268,
  16,
  11,
  1128,
  2975,
  7215,
  492,
  14,
  2975,
  448,
  175,
  945,
  332,
  2,
  142,
  138,
  185,
  100,
  9,
  2,
  19,
  239,
  42,
  1144,
  531,
  4460,
  144,
  99,
  267,
  22,
  2,
  1156,
  4,
  51,
  2975,
  183,
  25,
  761,
  166,
  2,
  4460],
 [3,
  268,
  16,
  11,
  651,
  2106,
  7215,
  492,
  14,
  2106,
  448,
  175,
  945,
  11,
  8,
  2,
  142,
  138,
  185,
  100,
  9,
  2,
  19,
  239,
  42,
  1144,
  96,
  1235,
  4460,
  144,
  99,
  267,
  22,
  2,
  1156,
  4,
  51,
  2106,
  183,
  25,
  761,
  2,
  4460,
  166,
  808],
 [3,
  268,
  545,
  11,
  651,
  135,
  499,
  492,
  14,
  2106,
  1199,
  175,
  945,
  11,
  8,
  2,
  142,
  138,
  503,
  100,
  9,
  2,
  19,
  239,
  42,
  1144,
  96,
  1235,
  4460,
  144,
  99,
  267,
  22,
  70,
  2508,
  4,
  51,
  2106,
  183,
  25,
  761,
  2,
  4460,
  166,
  808],
 [3,
  268,
  781,
  16,
  11,
  651,
  2106,
  7215,
  492,
  14,
  1129,
  2106,
  363,
  80,
  46,
  175,
  945,
  11,
  8,
  2,
  403,
  142,
  866,
  138,
  537,
  3,
  80,
  757,
  100,
  9,
  2,
  19,
  358,
  239,
  42,
  1144,
  96,
  1235,
  4460,
  144,
  99,
  47,
  267,
  22,
  2,
  1156,
  1156,
  4,
  6,
  51,
  2106,
  183,
  25,
  761,
  2,
  4460,
  166,
  808],
 [3,
  268,
  16,
  11,
  651,
  1235,
  7215,
  492,
  14,
  19,
  183,
  175,
  945,
  16,
  8,
  2,
  78,
  138,
  503,
  568,
  9,
  2,
  675,
  357,
  42,
  1144,
  96,
  1235,
  4460,
  144,
  99,
  1161,
  22,
  2,
  1156,
  4,
  51,
  2106,
  183,
  25,
  761,
  2,
  4460,
  10,
  808],
 [13773,
  358,
  1105,
  305,
  307,
  89,
  627,
  2,
  144,
  1876,
  9425,
  1827,
  357,
  12,
  1504,
  378,
  219,
  4294,
  13774,
  19,
  3,
  56,
  375,
  163,
  10,
  11,
  1069,
  3082,
  4,
  541],
 [13773,
  1105,
  307,
  627,
  2,
  8309,
  9425,
  1827,
  357,
  12,
  1504,
  219,
  4294,
  13774,
  19,
  3,
  56,
  127,
  163,
  10,
  11,
  2704,
  3082,
  4,
  541],
 [26655,
  1105,
  305,
  307,
  89,
  627,
  2,
  9425,
  6694,
  357,
  12,
  1119,
  193,
  219,
  4294,
  19,
  3,
  56,
  127,
  163,
  10,
  11,
  769,
  3082,
  4,
  541],
 [13773,
  358,
  1105,
  305,
  307,
  140,
  627,
  2,
  144,
  1876,
  9425,
  1827,
  357,
  12,
  1504,
  378,
  54,
  4294,
  13774,
  19,
  3,
  56,
  375,
  163,
  10,
  11,
  1069,
  3026,
  4,
  541],
 [1574,
  13773,
  358,
  1105,
  305,
  307,
  89,
  627,
  2,
  144,
  4604,
  1876,
  9425,
  1827,
  4295,
  357,
  6091,
  12,
  1504,
  378,
  219,
  4294,
  13774,
  340,
  19,
  3,
  56,
  50,
  80,
  46,
  163,
  10,
  11,
  1069,
  3082,
  691,
  4,
  541],
 [13773,
  358,
  30,
  305,
  307,
  89,
  627,
  2,
  288,
  1876,
  9425,
  1827,
  357,
  38,
  1504,
  378,
  219,
  644,
  13774,
  19,
  3,
  576,
  375,
  163,
  14,
  11,
  1069,
  3082,
  4,
  541],
 [882,
  2,
  2856,
  6695,
  21851,
  18120,
  5,
  13775,
  13776,
  2030,
  593,
  9,
  11,
  597,
  10116,
  1615,
  13777,
  144,
  18121,
  13778,
  676,
  1813,
  5,
  18122,
  20,
  243,
  13779,
  5,
  10117,
  10118,
  140],
 [882,
  2,
  777,
  6695,
  10119,
  16,
  18120,
  5,
  13775,
  13776,
  6092,
  9,
  11,
  6696,
  10116,
  1615,
  13777,
  6089,
  18121,
  13778,
  676,
  1813,
  5,
  26656,
  20,
  243,
  13779,
  5,
  10117,
  10118,
  140],
 [24064,
  2,
  777,
  6695,
  6695,
  7,
  26657,
  5,
  13775,
  26658,
  593,
  9,
  11,
  3179,
  10116,
  1615,
  18123,
  2390,
  4178,
  5824,
  676,
  4296,
  1352,
  20,
  243,
  176,
  5,
  10117,
  10118,
  140],
 [882,
  2,
  2856,
  6695,
  21851,
  18120,
  5,
  26659,
  13776,
  23,
  593,
  9,
  11,
  597,
  10116,
  1615,
  13777,
  144,
  8828,
  13778,
  2753,
  1813,
  5,
  18122,
  20,
  243,
  13779,
  5,
  10117,
  10118,
  140],
 [882,
  64,
  2,
  2856,
  5107,
  6695,
  21851,
  18120,
  5,
  13775,
  13776,
  47,
  2030,
  593,
  593,
  9,
  2149,
  11,
  597,
  10116,
  4605,
  1615,
  938,
  13777,
  144,
  18121,
  13778,
  676,
  1813,
  8829,
  5,
  18122,
  20,
  243,
  13779,
  2230,
  5,
  10117,
  10118,
  21852,
  140],
 [882,
  2,
  2856,
  5108,
  5303,
  26660,
  5,
  13775,
  13776,
  1106,
  593,
  9,
  111,
  597,
  10116,
  4606,
  13777,
  26661,
  18121,
  13778,
  676,
  10119,
  5,
  18122,
  20,
  243,
  26662,
  5,
  10117,
  10118,
  139],
 [144, 67, 47, 3, 3293, 6, 3669, 35, 2616, 994, 1476, 180, 1603, 110, 4757],
 [144, 67, 50, 3, 1604, 6, 3669, 35, 2616, 368, 400, 180, 1015, 110, 4757],
 [144, 67, 4, 1604, 6, 3669, 35, 2616, 368, 400, 180, 1015, 4757],
 [144, 67, 201, 3, 3293, 6, 3669, 35, 2616, 994, 1476, 180, 5304, 110, 4757],
 [144,
  67,
  47,
  4179,
  3,
  3293,
  6,
  3669,
  35,
  2616,
  26663,
  46,
  89,
  1476,
  180,
  610,
  1603,
  110,
  4757],
 [36, 67, 47, 3, 3293, 189, 3669, 35, 2616, 994, 3876, 180, 1603, 110, 4757],
 [28, 2, 144, 27, 1236, 441],
 [28, 2, 144, 27, 209, 4607],
 [28, 2, 144, 27, 95, 2809],
 [28, 2, 144, 74, 1236, 441],
 [1963, 28, 2, 144, 27, 1236, 441],
 [28, 2, 144, 27, 1236, 343],
 [248,
  197,
  291,
  144,
  72,
  2,
  972,
  19,
  51,
  8,
  87,
  358,
  28,
  2202,
  301,
  138,
  5,
  3,
  155,
  506,
  1044,
  31,
  3,
  1200,
  4,
  1674,
  16,
  376,
  14,
  2,
  244,
  1088,
  28,
  3,
  53,
  206,
  8,
  16,
  61,
  134,
  109,
  20,
  304,
  488,
  4,
  2,
  10120,
  5109,
  4297],
 [248,
  197,
  64,
  144,
  72,
  2,
  972,
  19,
  8,
  87,
  358,
  28,
  1353,
  301,
  561,
  5,
  3,
  155,
  1044,
  31,
  3,
  100,
  4,
  1674,
  14,
  2,
  244,
  1088,
  28,
  3,
  53,
  206,
  8,
  16,
  3,
  120,
  134,
  109,
  304,
  488,
  4,
  2,
  10120,
  8830,
  4297],
 [11,
  376,
  14,
  2,
  244,
  1088,
  28,
  3,
  53,
  206,
  8,
  16,
  61,
  304,
  488,
  4,
  54,
  18124,
  8831],
 [248,
  197,
  291,
  144,
  72,
  2,
  404,
  19,
  51,
  8,
  87,
  358,
  28,
  2202,
  301,
  138,
  5,
  3,
  155,
  506,
  1044,
  31,
  3,
  1200,
  4,
  1674,
  2,
  376,
  14,
  4,
  219,
  1088,
  28,
  3,
  53,
  206,
  8,
  16,
  61,
  134,
  109,
  20,
  304,
  488,
  4,
  125,
  10120,
  5109,
  4297],
 [248,
  197,
  291,
  144,
  72,
  2,
  972,
  19,
  3,
  51,
  8,
  87,
  358,
  28,
  2202,
  301,
  138,
  5,
  378,
  3,
  155,
  506,
  1044,
  109,
  31,
  282,
  3,
  576,
  1200,
  4,
  1674,
  16,
  305,
  376,
  14,
  2,
  244,
  854,
  1088,
  28,
  3,
  53,
  206,
  8,
  16,
  61,
  134,
  209,
  109,
  20,
  488,
  304,
  488,
  4,
  2,
  10120,
  3585,
  5109,
  4297],
 [248,
  197,
  291,
  144,
  113,
  2,
  972,
  19,
  51,
  8,
  87,
  358,
  28,
  2202,
  233,
  138,
  5,
  3,
  155,
  506,
  1044,
  370,
  3,
  1200,
  4,
  1674,
  16,
  376,
  8,
  2,
  244,
  1088,
  25,
  3,
  53,
  206,
  36,
  289,
  26664,
  134,
  109,
  20,
  304,
  488,
  4,
  2,
  3877,
  5109,
  4297],
 [1016, 130, 55, 13780, 5554, 336, 520, 3968, 643],
 [3, 59, 130, 55, 13780, 5554, 212, 520, 8311, 643],
 [59, 130, 55, 26665, 5554, 293, 336, 520, 3968, 643],
 [1016, 130, 55, 13780, 5554, 336, 520, 3968, 643],
 [1016, 108, 130, 604, 55, 13780, 5554, 64, 336, 520, 520, 3968, 643],
 [47, 130, 55, 13780, 60, 42, 146, 3968, 643],
 [231, 1306, 45, 7, 2, 1530, 350, 13781],
 [1306, 45, 7, 2, 1530, 3502, 13781],
 [231, 1306, 45, 7, 2, 398, 2976, 7, 3502],
 [231, 4, 45, 7, 2, 1530, 350, 13781],
 [995, 231, 1306, 45, 7, 2, 1530, 350, 13781],
 [231, 1306, 45, 7, 2, 1530, 1628, 13781],
 [67, 2, 320, 27, 38, 193, 2464, 442, 250],
 [67, 2, 320, 27, 38, 250, 193, 2464, 442],
 [67, 2, 320, 27, 38, 250, 9, 2464, 442],
 [67, 2, 320, 27, 2079, 193, 2464, 442, 250],
 [67, 2, 320, 27, 3670, 38, 193, 2464, 442, 691, 250],
 [9, 2, 320, 27, 38, 193, 2464, 442, 250],
 [62, 6, 654],
 [62, 6, 5825],
 [62, 531, 654],
 [62, 6, 654],
 [62, 6, 3878],
 [560,
  3,
  120,
  1016,
  11,
  141,
  90,
  5110,
  123,
  13782,
  9,
  379,
  445,
  22,
  1366,
  134,
  144,
  31,
  5,
  2,
  2176,
  8,
  8312],
 [560,
  61,
  1016,
  11,
  141,
  90,
  5110,
  123,
  13782,
  9,
  232,
  1179,
  22,
  6,
  1366,
  134,
  144,
  31,
  5,
  2,
  2176,
  8,
  8312],
 [560,
  3,

In [44]:
len(sequences[0])

12

In [45]:
from keras.utils import pad_sequences

In [46]:
sequences=pad_sequences(sequences,padding='pre')

In [47]:
sequences

array([[   0,    0,    0, ...,  435,   13,   28],
       [   0,    0,    0, ...,  435,   13,   28],
       [   0,    0,    0, ..., 1811,   13,   28],
       ...,
       [   0,    0,    0, ...,  117, 1033, 2159],
       [   0,    0,    0, ...,   80,   46, 2159],
       [   0,    0,    0, ...,    3, 1033, 2159]],
      shape=(71655, 166), dtype=int32)

Making RNN layer now

In [49]:
from tensorflow.keras.layers import SimpleRNN,Dense,Input,Embedding
from tensorflow.keras.models import Sequential

In [50]:
X=sequences

In [51]:
y=train['Sentiment'].values

In [52]:
X

array([[   0,    0,    0, ...,  435,   13,   28],
       [   0,    0,    0, ...,  435,   13,   28],
       [   0,    0,    0, ..., 1811,   13,   28],
       ...,
       [   0,    0,    0, ...,  117, 1033, 2159],
       [   0,    0,    0, ...,   80,   46, 2159],
       [   0,    0,    0, ...,    3, 1033, 2159]],
      shape=(71655, 166), dtype=int32)

In [53]:
y

array([3, 3, 3, ..., 3, 3, 3], shape=(71655,))

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [56]:
X_train.shape

(57324, 166)

In [67]:
model=Sequential()
model.add(SimpleRNN(32,input_shape=(166,1),return_sequences=False))
model.add(Dense(4,activation='softmax'))

c:\GENAI\Deep Learning ANN PROJECT\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [68]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │           132 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,220 (4.77 KB)

 Trainable params: 1,220 (4.77 KB)

 Non-trainable params: 0 (0.00 B)

In [69]:
model.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [70]:
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test),batch_size=64)

Epoch 1/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.2966 - loss: 1.3702 - val_accuracy: 0.2728 - val_loss: 1.3654
Epoch 2/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.2976 - loss: 1.3686 - val_accuracy: 0.3129 - val_loss: 1.3630
Epoch 3/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.2968 - loss: 1.3691 - val_accuracy: 0.3130 - val_loss: 1.3685
Epoch 4/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.2973 - loss: 1.3688 - val_accuracy: 0.3101 - val_loss: 1.3648
Epoch 5/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.2950 - loss: 1.3675 - val_accuracy: 0.3106 - val_loss: 1.3622
Epoch 6/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.3003 - loss: 1.3664 - val_accuracy: 0.3107 - val_loss: 1.3625
Epoch 7/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.2970 - loss: 1.3663 - val_accuracy: 0.3130 - val_loss: 1.3620
Epoch 8/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.2980 - loss: 1.3662 - val_accuracy: 0.3117 - val_loss: 1.3645
Epoch 9/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.2954 - loss: 1.3688 - val_accuracy: 0.3123 - val_loss: 1.3633
Epoch 10/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.2976 - loss: 1.3674 - val_accuracy: 0.3121 - val_loss: 1.3627

In [71]:
vocab_size=len(tokenizer.word_index) + 1

In [72]:
vocab_size

33785

In [73]:
model_2=Sequential()
model_2.add(Input(shape=(166,)))
model_2.add(Embedding(input_dim=vocab_size,output_dim=64))
model_2.add(Dense(4,activation='softmax'))

In [74]:
model_2.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 166, 64)        │     2,162,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 166, 4)         │           260 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,162,500 (8.25 MB)

 Trainable params: 2,162,500 (8.25 MB)

 Non-trainable params: 0 (0.00 B)

In [75]:
model_final=Sequential([Embedding(input_dim=vocab_size,output_dim=128,input_length=166,mask_zero=True),
SimpleRNN(32),Dense(4,activation='softmax')])

c:\GENAI\Deep Learning ANN PROJECT\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [76]:
model_final.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [77]:
model_final.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [78]:
model_final.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test),batch_size=64)

Epoch 1/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 40s 43ms/step - accuracy: 0.6642 - loss: 0.8377 - val_accuracy: 0.8285 - val_loss: 0.4755
Epoch 2/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 41s 46ms/step - accuracy: 0.9138 - loss: 0.2403 - val_accuracy: 0.8448 - val_loss: 0.4401
Epoch 3/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 40s 45ms/step - accuracy: 0.9542 - loss: 0.1231 - val_accuracy: 0.8519 - val_loss: 0.4505
Epoch 4/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 39s 44ms/step - accuracy: 0.9645 - loss: 0.0909 - val_accuracy: 0.8472 - val_loss: 0.5092
Epoch 5/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 41s 46ms/step - accuracy: 0.9660 - loss: 0.0844 - val_accuracy: 0.8499 - val_loss: 0.5252
Epoch 6/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 42s 47ms/step - accuracy: 0.9698 - loss: 0.0749 - val_accuracy: 0.8411 - val_loss: 0.5777
Epoch 7/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 40s 45ms/step - accuracy: 0.9713 - loss: 0.0688 - val_accuracy: 0.8497 - val_loss: 0.5677
Epoch 8/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 39s 43ms/step - accuracy: 0.9706 - loss: 0.0714 - val_accuracy: 0.8462 - val_loss: 0.5863
Epoch 9/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 38s 43ms/step - accuracy: 0.9728 - loss: 0.0652 - val_accuracy: 0.8438 - val_loss: 0.6109
Epoch 10/10
896/896 ━━━━━━━━━━━━━━━━━━━━ 35s 39ms/step - accuracy: 0.9742 - loss: 0.0613 - val_accuracy: 0.8400 - val_loss: 0.6419

In [79]:
import pickle

In [80]:
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)

In [81]:
model_final.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.